apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7m7l
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-orxj-tenant/rhtap-demo-app/hacbs-test-project-7m7l@sha256:d6f99ee28b6639fcdd21a019f22e10d76b8a01d2e53697b86598281ce03603c3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
